# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('letra_a', models.CharField(max_length=200)),
                ('letra_b', models.CharField(max_length=200)),
                ('letra_c', models.CharField(max_length=200)),
                ('letra_d', models.CharField(max_length=200)),
                ('resposta', models.CharField(max_length=200)),
                ('obervacao', models.CharField(max_length=200)),
            ],
        ),
    ]
