# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0003_auto_20171025_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assuntos.Assunto'),
        ),
    ]
