# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_auto_20171010_2310'),
        ('turmas', '0004_turma_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Aluno')),
                ('turmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma')),
            ],
        ),
    ]
