# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='presenca',
            field=models.BooleanField(default=False),
        ),
    ]
