# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_turma_disciplina'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma'),
        ),
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(null=True, upload_to='arquivos/'),
        ),
    ]
