# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20171118_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
