# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20171118_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(to='forum.Comentario'),
        ),
    ]
