# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20171118_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(related_name='comentarios', to='forum.Comentario'),
        ),
    ]
