# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20171118_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
