# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20171119_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
