# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_turma_disciplina'),
        ('questionarios', '0003_remove_questionario_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='questionario',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma'),
        ),
    ]
