# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('aluno', 'Aluno'), ('professor', 'Professor')], max_length=8, null=True),
        ),
    ]
