# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20170930_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
            ],
            options={
                'permissions': (('pode_acessar_area_aluno', 'O usuario podera ver todas as funcionalidade da area aluno'),),
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
            ],
            options={
                'permissions': (('pode_acessar_area_professor', 'O usuario podera ver todas as funcionalidade da area professor'),),
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
            ],
            options={
                'permissions': (('pode_acessar_area_tutor', 'O usuario podera ver todas as funcionalidade da area tutor'),),
            },
            bases=('usuarios.usuario',),
        ),
    ]
