# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_aluno_professor_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': (('pode_acessar_area_aluno', 'pode acessar area aluno'),)},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': (('pode_acessar_area_professor', 'pode acessar area professor'),)},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('pode_acessar_area_tutor', 'pode acessar area tutor'),)},
        ),
    ]
