# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionarios', '0004_auto_20171026_2140'),
        ('usuarios', '0007_auto_20171010_2310'),
        ('questoes', '0004_auto_20171026_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.ManyToManyField(to='usuarios.Aluno')),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionarios.Questionario')),
                ('questoes_erradas', models.ManyToManyField(to='questoes.Questao')),
            ],
        ),
    ]
