# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20171010_2310'),
        ('questoes', '0004_auto_20171026_1306'),
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='alunos',
        ),
        migrations.AddField(
            model_name='resultado',
            name='alunos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Aluno'),
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='questoes_erradas',
        ),
        migrations.AddField(
            model_name='resultado',
            name='questoes_erradas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questoes.Questao'),
        ),
    ]
