# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0004_auto_20171026_1306'),
        ('usuarios', '0007_auto_20171010_2310'),
        ('resultados', '0002_auto_20171029_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='alunos',
        ),
        migrations.AddField(
            model_name='resultado',
            name='alunos',
            field=models.ManyToManyField(to='usuarios.Aluno'),
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='questoes_erradas',
        ),
        migrations.AddField(
            model_name='resultado',
            name='questoes_erradas',
            field=models.ManyToManyField(to='questoes.Questao'),
        ),
    ]
