# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0004_auto_20171026_1306'),
        ('resultados', '0005_auto_20171029_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultados',
            new_name='Resultado',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='questoes_erradas',
        ),
        migrations.AddField(
            model_name='resultado',
            name='questoes_respondidas',
            field=models.ManyToManyField(to='questoes.Questao'),
        ),
    ]
