# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20171010_2310'),
        ('resultados', '0006_auto_20171029_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='questoes_respondidas',
            new_name='questoes_erradas',
        ),
        migrations.AddField(
            model_name='resultado',
            name='aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Aluno'),
        ),
    ]
