# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0007_auto_20171029_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.Questionario'),
        ),
    ]
