# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0008_auto_20171029_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Aluno'),
        ),
    ]
