# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_auto_20171010_2310'),
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('alunos', models.ManyToManyField(to='usuarios.Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Professor')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Tutor')),
            ],
        ),
    ]
