# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='alunos', to='usuarios.Aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='disciplinas.Disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='usuarios.Professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='usuarios.Tutor'),
        ),
    ]
