# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_auto_20171014_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
    ]
