# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('turmas', '0003_remove_turma_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='disciplinas.Disciplina'),
        ),
    ]
